#!/bin/sh

PREVIOUS_VERSION="`jq -r .version.version`"
TIMESTAMP="`date -u +'%Y-%m-%dT%H:%M:%SZ'`"
VERSION="${TIMESTAMP//:/-}"

if [ null = "$PREVIOUS_VERSION" ] || [ "|$PREVIOUS_VERSION" '<' "|$VERSION" ] || [ -z "$PREVIOUS_VERSION" ]; then
  cat <<EOF
[{
  "version": "$VERSION",
  "timestamp": "$TIMESTAMP"
}]
EOF
else
  echo "[]"
fi
